# These are supported funding model platforms

github: [GuitarML] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: GuitarML
custom: https://www.paypal.com/donate?business=H22K2S7B7ACMJ&no_recurring=0&item_name=Support+GuitarML&currency_code=USD
